# Generated by Django 5.2.1 on 2025-05-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='expires_at',
            new_name='expiry_at',
        ),
    ]
