# Generated by Django 5.2.1 on 2025-05-19 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='company_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
